# Generated by Django 3.2.4 on 2021-06-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Centre', '0003_auto_20210609_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Centre.patient'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='Pratiquant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Centre.pratiquant'),
        ),
    ]
