# Generated by Django 3.2.4 on 2021-06-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Centre', '0004_auto_20210609_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='TelPatient',
        ),
    ]
